# Generated by Django 4.2.30 on 2026-06-04 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('date', models.DateField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('url', models.URLField(blank=True)),
                ('program_payload', models.JSONField(blank=True, default=dict)),
                ('last_scraped', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['date', 'name', 'external_id'],
            },
        ),
        migrations.CreateModel(
            name='RaceResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=120, unique=True)),
                ('source', models.CharField(blank=True, max_length=255)),
                ('race_number', models.PositiveIntegerField(blank=True, null=True)),
                ('race_date_day', models.CharField(blank=True, max_length=20)),
                ('event', models.CharField(blank=True, max_length=255)),
                ('phase', models.CharField(blank=True, max_length=120)),
                ('position', models.PositiveIntegerField(blank=True, null=True)),
                ('master_class', models.CharField(blank=True, max_length=20)),
                ('finish_time', models.CharField(blank=True, max_length=40)),
                ('lane', models.PositiveIntegerField(blank=True, null=True)),
                ('bib', models.PositiveIntegerField(blank=True, null=True)),
                ('club', models.CharField(blank=True, max_length=255)),
                ('athletes', models.JSONField(blank=True, default=list)),
                ('gap', models.CharField(blank=True, max_length=40)),
                ('status', models.CharField(blank=True, max_length=120)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='races.race')),
            ],
            options={
                'ordering': ['race', 'race_number', 'position', 'club'],
            },
        ),
        migrations.CreateModel(
            name='RaceSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='races.race')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='race_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['race__date', 'race__name', 'user__username'],
                'unique_together': {('user', 'race')},
            },
        ),
    ]
