# Generated by Django 5.2.14 on 2026-05-11 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_bookableslot_bookableslot_unique_bookable_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookableslot',
            name='day_of_week',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Lunedì'), (1, 'Martedì'), (2, 'Mercoledì'), (3, 'Giovedì'), (4, 'Venerdì'), (5, 'Sabato'), (6, 'Domenica')]),
        ),
    ]
