# Generated by Django 4.2.30 on 2026-05-16 16:22

from django.db import migrations, models
import django.db.models.deletion


def backfill_slot_batch_links(apps, schema_editor):
    Slot = apps.get_model('bookings', 'Slot')
    SlotBatchSlot = apps.get_model('bookings', 'SlotBatchSlot')
    links = [
        SlotBatchSlot(batch_id=slot.batch_id, slot_id=slot.id)
        for slot in Slot.objects.exclude(batch_id__isnull=True).only('id', 'batch_id')
    ]
    SlotBatchSlot.objects.bulk_create(links, ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_robust_booking_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'Maschio'), ('F', 'Femmina'), ('O', 'Altro')], max_length=1),
        ),
        migrations.CreateModel(
            name='SlotBatchSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_links', to='bookings.slotbatch')),
                ('slot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='batch_link', to='bookings.slot')),
            ],
            options={
                'ordering': ['slot__date', 'slot__start_time'],
            },
        ),
        migrations.RunPython(backfill_slot_batch_links, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='slotbatchslot',
            constraint=models.UniqueConstraint(fields=('batch', 'slot'), name='unique_slot_batch_link'),
        ),
    ]
