# Generated by Django 4.2.30 on 2026-05-16 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_alter_athlete_sex'),
        ('bookings', '0005_alter_athlete_sex_slotbatchslot_and_more'),
    ]

    operations = [
    ]
